services:
  - type: web
    name: fakestore-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fakestore.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fakestore.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False